language: ruby
services: memcache
before_install:
  - gem update bundler
rvm:
  - 2.2.6
  - 2.3.3
env:
  - "AS_VERSION=4.0.5"
  - "AS_VERSION=4.1.0"
  - "AS_VERSION=4.2.0"
  - "AS_VERSION=5.0.0"
notifications:
  email: false
