sudo: false
cache: bundler
language: ruby
services: memcache

rvm:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - "AS_VERSION=5.2.0"
  - "AS_VERSION=6.0.0"

jobs:
  exclude:
    - rvm: "2.7"
      env: "AS_VERSION=5.2.0"

notifications:
  email: false
